In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('wages.csv')
df.head()

           earn  height     sex   race  ed  age
0  79571.299011   73.89    male  white  16   49
1  96396.988643   66.23  female  white  16   62
2  48710.666947   63.77  female  white  16   33
3  80478.096153   63.22  female  other  16   95
4  82089.345498   63.08  female  white  17   43

In [3]:
df

              earn  height     sex   race  ed  age
0     79571.299011   73.89    male  white  16   49
1     96396.988643   66.23  female  white  16   62
2     48710.666947   63.77  female  white  16   33
3     80478.096153   63.22  female  other  16   95
4     82089.345498   63.08  female  white  17   43
...            ...     ...     ...    ...  ..  ...
1374  30173.380363   71.68    male  white  12   33
1375  24853.519514   61.31  female  white  18   86
1376  13710.671312   63.64  female  white  12   37
1377  95426.014410   71.65    male  white  12   54
1378   9575.461857   68.22    male  white  12   31

[1379 rows x 6 columns]

In [4]:
df.describe()  #숫자로 이루어진 데이터의 요약정보

                earn       height           ed          age
count    1379.000000  1379.000000  1379.000000  1379.000000
mean    32446.292622    66.592640    13.354605    45.328499
std     31257.070006     3.818108     2.438741    15.789715
min       -98.580489    57.340000     3.000000    22.000000
25%     10538.790721    63.720000    12.000000    33.000000
50%     26877.870178    66.050000    13.000000    42.000000
75%     44506.215336    69.315000    15.000000    55.000000
max    317949.127955    77.210000    18.000000    95.000000

In [5]:
len(df) # 0부터 1378까지 총 1379개의 데이터

1379

In [6]:
df.race

0       white
1       white
2       white
3       other
4       white
        ...
1374    white
1375    white
1376    white
1377    white
1378    white
Name: race, Length: 1379, dtype: object

In [7]:
df['race'].unique() #df.race.unique()

array(['white', 'other', 'hispanic', 'black'], dtype=object)

In [8]:
import numpy as np

In [9]:
np.array(dict(enumerate(df['race'].unique())))

array({0: 'white', 1: 'other', 2: 'hispanic', 3: 'black'}, dtype=object)

In [11]:
print(df)
df.sum(axis=0) #column별, axis=0 안적어도 기본으로 axis=0이라 괜찮음

              earn  height     sex   race  ed  age
0     79571.299011   73.89    male  white  16   49
1     96396.988643   66.23  female  white  16   62
2     48710.666947   63.77  female  white  16   33
3     80478.096153   63.22  female  other  16   95
4     82089.345498   63.08  female  white  17   43
...            ...     ...     ...    ...  ..  ...
1374  30173.380363   71.68    male  white  12   33
1375  24853.519514   61.31  female  white  18   86
1376  13710.671312   63.64  female  white  12   37
1377  95426.014410   71.65    male  white  12   54
1378   9575.461857   68.22    male  white  12   31

[1379 rows x 6 columns]

earn                                            4.47434e+07
height                                              91831.2
sex       malefemalefemalefemalefemalefemalefemalemalema...
race      whitewhitewhiteotherwhitewhitewhitewhitehispan...
ed                                                    18416
age                                                   62508
dtype: object

In [12]:
df.sum(axis=1) #row별, race,sex와 같은 문자열은 빼고 숫자만 더함

0       79710.189011
1       96541.218643
2       48823.436947
3       80652.316153
4       82212.425498
            ...
1374    30290.060363
1375    25018.829514
1376    13823.311312
1377    95563.664410
1378     9686.681857
Length: 1379, dtype: float64

In [13]:
df.isnull() #모두 false라고 나오는 이유는 빈칸이 없어서임

       earn  height    sex   race     ed    age
0     False   False  False  False  False  False
1     False   False  False  False  False  False
2     False   False  False  False  False  False
3     False   False  False  False  False  False
4     False   False  False  False  False  False
...     ...     ...    ...    ...    ...    ...
1374  False   False  False  False  False  False
1375  False   False  False  False  False  False
1376  False   False  False  False  False  False
1377  False   False  False  False  False  False
1378  False   False  False  False  False  False

[1379 rows x 6 columns]

In [14]:
df.isnull().sum()

earn      0
height    0
sex       0
race      0
ed        0
age       0
dtype: int64

In [16]:
df.sort_values(['earn','age'],ascending=True).head(10) #ascending=False로 하면 내림차순 정렬. 'earn','age'라고 적었으므로 'earn'으로 먼저 오름차순 정렬 후 'age'로 오름차순 정렬

           earn  height   sex      race  ed  age
899  -98.580489   69.12  male     white  13   24
29   -95.710279   68.46  male     white  11   25
1039 -66.128300   72.92  male     black  12   24
1038 -56.321979   67.81  male  hispanic  10   22
1236 -49.597624   70.96  male     other  12   24
1072 -30.423502   72.38  male     black  12   23
800  -27.876819   72.29  male     white  12   22
963  -25.655260   68.90  male     white  12   22
422  -12.016714   72.08  male     white   8   24
1194  -1.509370   64.92  male     white  12   59

In [17]:
df.sort_values(['age','earn'],ascending=False)[:10]

              earn  height     sex   race  ed  age
3     80478.096153   63.22  female  other  16   95
809   42963.362005   72.94    male  white  12   95
331   39169.750135   64.79  female  white  12   95
102   39751.194030   67.14    male  white  12   93
993   32809.632677   59.61  female  other  16   92
1017   8942.806716   62.97  female  white  10   91
1192  39757.947210   64.79    male  white  16   90
952    8162.682672   58.09  female  white   5   89
827   55712.348432   70.13    male  white   9   88
939   40744.874765   59.15  female  white  15   87

In [18]:
df.age

0       49
1       62
2       33
3       95
4       43
        ..
1374    33
1375    86
1376    37
1377    54
1378    31
Name: age, Length: 1379, dtype: int64

In [19]:
df.head()

           earn  height     sex   race  ed  age
0  79571.299011   73.89    male  white  16   49
1  96396.988643   66.23  female  white  16   62
2  48710.666947   63.77  female  white  16   33
3  80478.096153   63.22  female  other  16   95
4  82089.345498   63.08  female  white  17   43

In [20]:
df.age.corr(df.earn)#상관계수, 반대로한 df.earn.corr(df.age)이랑 결과같음,아래참조

0.07400349177836055

In [21]:
df['earn'].corr(df.age)

0.07400349177836055

In [22]:
df['age'].cov(df['earn'])#공분산, 마찬가지로 반대로 해도 무방,아래참조

36523.6992104089

In [23]:
df.earn.cov(df.age)

36523.6992104089

In [24]:
df.corrwith(df.earn) #earn과 다른 데이터들과의 상관관계, earn과의 상관관계는 1, 성별과 인종은 문자열 데이터라 안나옴

earn      1.000000
height    0.291600
ed        0.350374
age       0.074003
dtype: float64

In [25]:
df.corr() #df의 모든 상관관계 조합

            earn    height        ed       age
earn    1.000000  0.291600  0.350374  0.074003
height  0.291600  1.000000  0.114047 -0.133727
ed      0.350374  0.114047  1.000000 -0.129802
age     0.074003 -0.133727 -0.129802  1.000000

In [26]:
df[:4]

           earn  height     sex   race  ed  age
0  79571.299011   73.89    male  white  16   49
1  96396.988643   66.23  female  white  16   62
2  48710.666947   63.77  female  white  16   33
3  80478.096153   63.22  female  other  16   95

In [27]:
df.groupby('race')['earn'].sum() #race를 기준으로 earn의 sum을 구함

race
black       3.574884e+06
hispanic    1.962368e+06
other       9.360450e+05
white       3.827014e+07
Name: earn, dtype: float64

In [28]:
df.groupby(['sex','race'])['earn'].sum()

sex     race
female  black       2.113063e+06
        hispanic    9.759982e+05
        other       6.149582e+05
        white       1.712299e+07
male    black       1.461821e+06
        hispanic    9.863701e+05
        other       3.210868e+05
        white       2.114715e+07
Name: earn, dtype: float64

In [29]:
df.groupby(['race','sex'])['earn'].sum()

race      sex
black     female    2.113063e+06
          male      1.461821e+06
hispanic  female    9.759982e+05
          male      9.863701e+05
other     female    6.149582e+05
          male      3.210868e+05
white     female    1.712299e+07
          male      2.114715e+07
Name: earn, dtype: float64

In [30]:
grouped=df.groupby('race')
for a,b in grouped: #a는 race, b는 해당race의 value값들
  print(a)
  print(b)

black
              earn  height     sex   race  ed  age
21    12131.822115   64.20  female  black  12   59
22    84223.397919   72.76    male  black  13   39
28    16896.100044   62.76  female  black  12   39
42    48693.479796   67.19  female  black  14   35
55    20594.711211   66.35    male  black   8   60
...            ...     ...     ...    ...  ..  ...
1288  31868.479340   71.49    male  black  12   30
1295  24857.441360   67.82  female  black  11   35
1356   6354.842127   70.09    male  black  14   25
1363  19182.607431   73.26    male  black  13   25
1366  24849.193294   60.30  female  black  12   80

[126 rows x 6 columns]
hispanic
              earn  height     sex      race  ed  age
8      3212.649556   72.24    male  hispanic  15   25
51    18497.853893   60.61  female  hispanic  12   25
70    25550.755908   62.04    male  hispanic  14   32
86     4812.715281   67.12  female  hispanic   8   43
87    47742.125275   68.19    male  hispanic  12   36
...            ...     ...     ...       ...  ..  ...
1329  27044.398985   70.96    male  hispanic  13   40
1333  58234.580965   63.60  female  hispanic  17   38
1334  15865.726828   71.90    male  hispanic  13   24
1368   4184.222685   60.19  female  hispanic   6   71
1369   4755.736508   72.94    male  hispanic  15   24

[77 rows x 6 columns]
other
               earn  height     sex   race  ed  age
3      80478.096153   63.22  female  other  16   95
119      996.182111   66.31  female  other  16   36
157    34383.704520   68.07  female  other  12   54
223    31727.703585   66.64    male  other  10   32
230    51892.942388   65.68  female  other  18   39
260    13718.454392   64.51  female  other  10   86
295     5764.826401   66.36  female  other  12   39
339    10565.080348   62.79  female  other  12   35
524    64598.456297   59.72  female  other  18   39
594    23877.347633   65.08    male  other  14   25
625    24855.035494   61.20  female  other  16   38
662    44600.177062   66.41    male  other  15   44
708     1023.988921   62.99  female  other   8   56
764    60492.121231   67.04    male  other  17   58
791      987.960797   61.66  female  other  17   30
879    44447.409957   74.83    male  other  16   38
972    35979.200227   62.73  female  other  18   63
993    32809.632677   59.61  female  other  16   92
998    24854.104206   64.02  female  other  13   37
1015    8026.645794   62.04  female  other   6   76
1153    7364.532140   64.81  female  other  12   32
1156   27130.701913   69.07    male  other  14   37
1236     -49.597624   70.96    male  other  12   24
1243   28575.385564   62.05    male  other  16   31
1277   12721.568402   65.93    male  other  10   64
1279   39687.720336   61.89    male  other  14   41
1298    7876.230872   69.78    male  other  13   26
1367   40757.935077   64.17  female  other  16   41
1370  175901.453598   65.90  female  other  18   52
white
              earn  height     sex   race  ed  age
0     79571.299011   73.89    male  white  16   49
1     96396.988643   66.23  female  white  16   62
2     48710.666947   63.77  female  white  16   33
4     82089.345498   63.08  female  white  17   43
5     15313.352901   64.53  female  white  15   30
...            ...     ...     ...    ...  ..  ...
1374  30173.380363   71.68    male  white  12   33
1375  24853.519514   61.31  female  white  18   86
1376  13710.671312   63.64  female  white  12   37
1377  95426.014410   71.65    male  white  12   54
1378   9575.461857   68.22    male  white  12   31

[1147 rows x 6 columns]

In [31]:
grouped2=df.groupby('sex')
for c,d in grouped2:
  print('hg',c,2423) 
  print('fwe',d,"gwee")

hg female 2423
fwe                earn  height     sex      race  ed  age
1      96396.988643   66.23  female     white  16   62
2      48710.666947   63.77  female     white  16   33
3      80478.096153   63.22  female     other  16   95
4      82089.345498   63.08  female     white  17   43
5      15313.352901   64.53  female     white  15   30
...             ...     ...     ...       ...  ..  ...
1368    4184.222685   60.19  female  hispanic   6   71
1370  175901.453598   65.90  female     other  18   52
1373   16905.557851   70.08  female     white  16   40
1375   24853.519514   61.31  female     white  18   86
1376   13710.671312   63.64  female     white  12   37

[859 rows x 6 columns] gwee
hg male 2423
fwe               earn  height   sex      race  ed  age
0     79571.299011   73.89  male     white  16   49
7     50960.054282   73.29  male     white  17   50
8      3212.649556   72.24  male  hispanic  15   25
9     42996.637884   72.40  male     white  12   30
10    10328.618843   70.22  male     white  16   69
...            ...     ...   ...       ...  ..  ...
1371  87473.968778   68.82  male     white  18   75
1372  92205.596106   69.62  male     white  18   57
1374  30173.380363   71.68  male     white  12   33
1377  95426.014410   71.65  male     white  12   54
1378   9575.461857   68.22  male     white  12   31

[520 rows x 6 columns] gwee

In [32]:
grouped=df.groupby('sex')
grouped.get_group('male') #key값이 male인 value값들을 그룹으로 가져옴, 바로 위에랑 확인해보삼

              earn  height   sex      race  ed  age
0     79571.299011   73.89  male     white  16   49
7     50960.054282   73.29  male     white  17   50
8      3212.649556   72.24  male  hispanic  15   25
9     42996.637884   72.40  male     white  12   30
10    10328.618843   70.22  male     white  16   69
...            ...     ...   ...       ...  ..  ...
1371  87473.968778   68.82  male     white  18   75
1372  92205.596106   69.62  male     white  18   57
1374  30173.380363   71.68  male     white  12   33
1377  95426.014410   71.65  male     white  12   54
1378   9575.461857   68.22  male     white  12   31

[520 rows x 6 columns]

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas import DataFrame
df1 = pd.DataFrame({'key1':['k','b','k','c','k','k','b'],
                    'data1':range(7)})
df2 = pd.DataFrame({'key1':['k','b','b','d'],
                 'data2':np.arange(4)})

In [34]:
df1

  key1  data1
0    k      0
1    b      1
2    k      2
3    c      3
4    k      4
5    k      5
6    b      6

In [35]:
df2

  key1  data2
0    k      0
1    b      1
2    b      2
3    d      3

In [36]:
pd.merge(df1,df2,on='key1',how='inner') #안겹치는 df1의 c와 df2의 d는 버림, on='key1'과 how='inner'은 생략가능

  key1  data1  data2
0    k      0      0
1    k      2      0
2    k      4      0
3    k      5      0
4    b      1      1
5    b      1      2
6    b      6      1
7    b      6      2

In [37]:
pd.merge(df1,df2,how='outer') # df1의 c와 df2의 d를 살림

  key1  data1  data2
0    k    0.0    0.0
1    k    2.0    0.0
2    k    4.0    0.0
3    k    5.0    0.0
4    b    1.0    1.0
5    b    1.0    2.0
6    b    6.0    1.0
7    b    6.0    2.0
8    c    3.0    NaN
9    d    NaN    3.0

In [38]:
pd.merge(df1,df2,how='left') # df1의 c를 살림

  key1  data1  data2
0    k      0    0.0
1    b      1    1.0
2    b      1    2.0
3    k      2    0.0
4    c      3    NaN
5    k      4    0.0
6    k      5    0.0
7    b      6    1.0
8    b      6    2.0

In [39]:
df=pd.DataFrame({'a':{1:'a',2:'aa',3:'aaa'},'b':{1:'b',2:'bb'}})
df

     a    b
1    a    b
2   aa   bb
3  aaa  NaN

In [40]:
data1={'a':{1:'a',2:'aa',3:'aaa'},'b':{1:'b',2:'bb'}}
df2=pd.DataFrame(data1) # 만약 pd. 이거 안쓰고 DataFrame으로만 쓰고 싶다면 from pandas import DataFrame 해주면 됨.
df2

     a    b
1    a    b
2   aa   bb
3  aaa  NaN

In [41]:
import pandas as pd
sample=pd.read_csv('CMAPSS_sample.txt')
sample.head()

  1 1 0.0023 0.0003 100.0 518.67 643.02 1585.29 1398.21 14.62 21.61 553.90 2388.04 9050.17 1.30 47.20 521.72 2388.03 8125.55 8.4052 0.03 392 2388 100.00 38.86 23.3735
0  1 2 -0.0027 -0.0003 100.0 518.67 641.71 1588.4...
1  1 3 0.0003 0.0001 100.0 518.67 642.46 1586.94 ...
2  1 4 0.0042 0.0000 100.0 518.67 642.44 1584.12 ...
3  1 5 0.0014 0.0000 100.0 518.67 642.51 1587.19 ...
4  1 6 0.0012 0.0003 100.0 518.67 642.11 1579.12 ...

In [42]:
sample=pd.read_csv('CMAPSS_sample.txt',sep=' ',header=None) #header=None : column값이 없다는 의미
sample.head()

   0   1       2       3      4       5   ...    22     23     24       25  26  27
0   1   1  0.0023  0.0003  100.0  518.67  ...  2388  100.0  38.86  23.3735 NaN NaN
1   1   2 -0.0027 -0.0003  100.0  518.67  ...  2388  100.0  39.02  23.3916 NaN NaN
2   1   3  0.0003  0.0001  100.0  518.67  ...  2388  100.0  39.08  23.4166 NaN NaN
3   1   4  0.0042  0.0000  100.0  518.67  ...  2388  100.0  39.00  23.3737 NaN NaN
4   1   5  0.0014  0.0000  100.0  518.67  ...  2388  100.0  38.99  23.4130 NaN NaN

[5 rows x 28 columns]

In [43]:
sample.drop([26, 27],axis=1, inplace=True) #axis=1까지만 하면 drop된 상태를 보여주기만할뿐 다시 sample 출력하면 그대로임. 따라서 inplace=True 필요. (저장느낌)
sample.head()

   0   1       2       3      4   ...   21    22     23     24       25
0   1   1  0.0023  0.0003  100.0  ...  392  2388  100.0  38.86  23.3735
1   1   2 -0.0027 -0.0003  100.0  ...  393  2388  100.0  39.02  23.3916
2   1   3  0.0003  0.0001  100.0  ...  393  2388  100.0  39.08  23.4166
3   1   4  0.0042  0.0000  100.0  ...  391  2388  100.0  39.00  23.3737
4   1   5  0.0014  0.0000  100.0  ...  390  2388  100.0  38.99  23.4130

[5 rows x 26 columns]

In [44]:
a=['UnitNumber','Cycle']
b=['Op_Setting_'+str(i) for i in range(1,4)] # str(i) : 문자열i
c=['Sensor_'+str(i)for i in range(1,22)]
d=a+b+c
sample.columns=d # sample.columns=a+b+c라 해도됨
sample.head()

   UnitNumber  Cycle  Op_Setting_1  ...  Sensor_19  Sensor_20  Sensor_21
0           1      1        0.0023  ...      100.0      38.86    23.3735
1           1      2       -0.0027  ...      100.0      39.02    23.3916
2           1      3        0.0003  ...      100.0      39.08    23.4166
3           1      4        0.0042  ...      100.0      39.00    23.3737
4           1      5        0.0014  ...      100.0      38.99    23.4130

[5 rows x 26 columns]

In [45]:
sample['UnitNumber']==77 #바로 아래보면 알수있듯이 9920부터 10081까지 77이므로 이 범위내에선 True값이 나올것

0        False
1        False
2        False
3        False
4        False
         ...
13091    False
13092    False
13093    False
13094    False
13095    False
Name: UnitNumber, Length: 13096, dtype: bool

In [46]:
sample[sample['UnitNumber']==77]

       UnitNumber  Cycle  Op_Setting_1  ...  Sensor_19  Sensor_20  Sensor_21
9920           77      1        0.0026  ...      100.0      39.06    23.4108
9921           77      2        0.0072  ...      100.0      38.94    23.2789
9922           77      3       -0.0019  ...      100.0      38.89    23.3391
9923           77      4       -0.0022  ...      100.0      39.03    23.3531
9924           77      5       -0.0016  ...      100.0      38.88    23.3224
...           ...    ...           ...  ...        ...        ...        ...
10077          77    158        0.0044  ...      100.0      38.82    23.0944
10078          77    159       -0.0014  ...      100.0      38.68    23.2850
10079          77    160       -0.0013  ...      100.0      38.72    23.2431
10080          77    161       -0.0013  ...      100.0      38.75    23.2021
10081          77    162       -0.0027  ...      100.0      38.75    23.1712

[162 rows x 26 columns]

In [47]:
sample_77=sample[sample['UnitNumber']==77]
sample_77

       UnitNumber  Cycle  Op_Setting_1  ...  Sensor_19  Sensor_20  Sensor_21
9920           77      1        0.0026  ...      100.0      39.06    23.4108
9921           77      2        0.0072  ...      100.0      38.94    23.2789
9922           77      3       -0.0019  ...      100.0      38.89    23.3391
9923           77      4       -0.0022  ...      100.0      39.03    23.3531
9924           77      5       -0.0016  ...      100.0      38.88    23.3224
...           ...    ...           ...  ...        ...        ...        ...
10077          77    158        0.0044  ...      100.0      38.82    23.0944
10078          77    159       -0.0014  ...      100.0      38.68    23.2850
10079          77    160       -0.0013  ...      100.0      38.72    23.2431
10080          77    161       -0.0013  ...      100.0      38.75    23.2021
10081          77    162       -0.0027  ...      100.0      38.75    23.1712

[162 rows x 26 columns]

In [48]:
df=sample_77.describe()
df

       UnitNumber       Cycle  Op_Setting_1  ...  Sensor_19   Sensor_20   Sensor_21
count       162.0  162.000000    162.000000  ...      162.0  162.000000  162.000000
mean         77.0   81.500000      0.000163  ...      100.0   38.877901   23.335781
std           0.0   46.909487      0.002246  ...        0.0    0.127515    0.075753
min          77.0    1.000000     -0.005300  ...      100.0   38.560000   23.078100
25%          77.0   41.250000     -0.001575  ...      100.0   38.782500   23.286250
50%          77.0   81.500000      0.000100  ...      100.0   38.880000   23.331650
75%          77.0  121.750000      0.001600  ...      100.0   38.977500   23.381200
max          77.0  162.000000      0.007200  ...      100.0   39.180000   23.558500

[8 rows x 26 columns]

In [49]:
s66=sample[sample.UnitNumber==65] #그냥 확인차 넣어봄
s66

      UnitNumber  Cycle  Op_Setting_1  ...  Sensor_19  Sensor_20  Sensor_21
8497          65      1       -0.0027  ...      100.0      39.13    23.3603
8498          65      2       -0.0031  ...      100.0      39.07    23.3845
8499          65      3        0.0014  ...      100.0      39.11    23.4761
8500          65      4       -0.0020  ...      100.0      38.98    23.5207
8501          65      5        0.0006  ...      100.0      38.97    23.4421
...          ...    ...           ...  ...        ...        ...        ...
8563          65     67       -0.0013  ...      100.0      38.96    23.3797
8564          65     68        0.0031  ...      100.0      38.90    23.5077
8565          65     69       -0.0017  ...      100.0      39.06    23.3182
8566          65     70        0.0008  ...      100.0      38.98    23.4418
8567          65     71        0.0012  ...      100.0      39.19    23.3270

[71 rows x 26 columns]

In [50]:
sample.head()

   UnitNumber  Cycle  Op_Setting_1  ...  Sensor_19  Sensor_20  Sensor_21
0           1      1        0.0023  ...      100.0      38.86    23.3735
1           1      2       -0.0027  ...      100.0      39.02    23.3916
2           1      3        0.0003  ...      100.0      39.08    23.4166
3           1      4        0.0042  ...      100.0      39.00    23.3737
4           1      5        0.0014  ...      100.0      38.99    23.4130

[5 rows x 26 columns]

In [51]:
series=sample.groupby('Cycle')['Sensor_11'].mean() #Cycle을 기준으로 Sensor_11의 평균을 구함
#아래에서 보면 알수있듯이 UnitNumber는 100까지있고, 각UnitNumber엔 Cycle의 수가 다 다르게 있음
series

Cycle
1      47.3432
2      47.3445
3      47.3156
4      47.3299
5      47.3266
        ...
299    47.8500
300    47.9200
301    47.8900
302    47.9300
303    48.0100
Name: Sensor_11, Length: 303, dtype: float64

In [52]:
max_cycle=sample.groupby('UnitNumber')['Cycle'].max()
max_cycle

UnitNumber
1       31
2       49
3      126
4      106
5       98
      ...
96      97
97     134
98     121
99      97
100    198
Name: Cycle, Length: 100, dtype: int64

In [53]:
max_cycle=sample.groupby('UnitNumber')['Cycle'].max().reset_index()
max_cycle

    UnitNumber  Cycle
0            1     31
1            2     49
2            3    126
3            4    106
4            5     98
..         ...    ...
95          96     97
96          97    134
97          98    121
98          99     97
99         100    198

[100 rows x 2 columns]

In [54]:
max_cycle[max_cycle.UnitNumber==77] #위에 sample_77참고하고 162맞는지 확인하라고.

    UnitNumber  Cycle
76          77    162

In [55]:
sample

       UnitNumber  Cycle  Op_Setting_1  ...  Sensor_19  Sensor_20  Sensor_21
0               1      1        0.0023  ...      100.0      38.86    23.3735
1               1      2       -0.0027  ...      100.0      39.02    23.3916
2               1      3        0.0003  ...      100.0      39.08    23.4166
3               1      4        0.0042  ...      100.0      39.00    23.3737
4               1      5        0.0014  ...      100.0      38.99    23.4130
...           ...    ...           ...  ...        ...        ...        ...
13091         100    194        0.0049  ...      100.0      38.65    23.1974
13092         100    195       -0.0011  ...      100.0      38.57    23.2771
13093         100    196       -0.0006  ...      100.0      38.62    23.2051
13094         100    197       -0.0038  ...      100.0      38.66    23.2699
13095         100    198        0.0013  ...      100.0      38.70    23.1855

[13096 rows x 26 columns]

In [56]:
df=pd.merge(max_cycle,sample,on='UnitNumber',how='inner')
df #Cycle_x:max_cycle의 Cycle에 의한 각UnitNumber별 Cycle의 최댓값, Cycle_y:sample의 Cycle값

       UnitNumber  Cycle_x  Cycle_y  ...  Sensor_19  Sensor_20  Sensor_21
0               1       31        1  ...      100.0      38.86    23.3735
1               1       31        2  ...      100.0      39.02    23.3916
2               1       31        3  ...      100.0      39.08    23.4166
3               1       31        4  ...      100.0      39.00    23.3737
4               1       31        5  ...      100.0      38.99    23.4130
...           ...      ...      ...  ...        ...        ...        ...
13091         100      198      194  ...      100.0      38.65    23.1974
13092         100      198      195  ...      100.0      38.57    23.2771
13093         100      198      196  ...      100.0      38.62    23.2051
13094         100      198      197  ...      100.0      38.66    23.2699
13095         100      198      198  ...      100.0      38.70    23.1855

[13096 rows x 27 columns]

In [57]:
sample['Remaning_Life']=df['Cycle_x']-sample['Cycle'] #새로운 Series 생성
sample

       UnitNumber  Cycle  Op_Setting_1  ...  Sensor_20  Sensor_21  Remaning_Life
0               1      1        0.0023  ...      38.86    23.3735             30
1               1      2       -0.0027  ...      39.02    23.3916             29
2               1      3        0.0003  ...      39.08    23.4166             28
3               1      4        0.0042  ...      39.00    23.3737             27
4               1      5        0.0014  ...      38.99    23.4130             26
...           ...    ...           ...  ...        ...        ...            ...
13091         100    194        0.0049  ...      38.65    23.1974              4
13092         100    195       -0.0011  ...      38.57    23.2771              3
13093         100    196       -0.0006  ...      38.62    23.2051              2
13094         100    197       -0.0038  ...      38.66    23.2699              1
13095         100    198        0.0013  ...      38.70    23.1855              0

[13096 rows x 27 columns]

In [58]:
# 오케이